import { PayloadAction, createSlice } from '@reduxjs/toolkit'
import { ComplexInitialState } from '../../../@types/redux/ComplexTypes/types'

const initialState: ComplexInitialState = {
	complexArray: [
		{
			id: 'naturalWhite-cabelWhite',
			cabel: 'input-roke-white',
			material: 'input-oak-natural',
			cabelTitle: 'Натуральный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item1.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item1.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item1.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
							'/pictures/complex/item1.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
		{
			id: 'lightWhite-cabelWhite',
			cabel: 'input-roke-white',
			material: 'input-oak-light',
			cabelTitle: 'Белёный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item2.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item2.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item2.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
							'/pictures/complex/item2.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
		{
			id: 'darkWhite-cabelWhite',
			cabel: 'input-roke-white',
			material: 'input-oak-dark',
			cabelTitle: 'Тёмный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item3.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item3.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item3.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
							'/pictures/complex/item3.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
		{
			id: 'naturalWhite-cabelBlack',
			cabel: 'input-roke-black',
			material: 'input-oak-natural',
			cabelTitle: 'Натуральный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item4.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item4.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item4.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
							'/pictures/complex/item4.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
		{
			id: 'lightWhite-cabelBlack',
			cabel: 'input-roke-black',
			material: 'input-oak-light',
			cabelTitle: 'Белёный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item5.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item5.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item5.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
							'/pictures/complex/item5.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
		{
			id: 'darkWhite-cabelBlack',
			cabel: 'input-roke-black',
			material: 'input-oak-dark',
			cabelTitle: 'Тёмный дуб',
			materialTitle: 'Белый канат',
			items: [
				{
					itemId: 'first',
					count: 1,
					src: '/pictures/complex/item6.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'second',
					count: 1,
					src: '/pictures/complex/item6.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
				{
					itemId: 'third',
					count: 1,
					src: '/pictures/complex/item6.jpg',
					price: 19.999,
					priceDiscount: 20.999,
					title: 'Когтеточка Бай',
					characteristics: [{ title: 'Дерево', text: 'Дуб' }],
					info: {
						src: [
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
							'/pictures/complex/item6.jpg',
						],
						description: [
							'Игровой комплекс для кошек в скандинавском стиле из натурального дуба, хлопкового каната, гипоаллергенного фильца, прочного микровелюра.',
						],
					},
				},
			],
		},
	],
	materialArray: [
		{
			id: 'input-oak-natural',
			src: '/pictures/combination/inputs/oak-natural.png',
		},
		{
			id: 'input-oak-light',
			src: '/pictures/combination/inputs/oak-light.png',
		},
		{
			id: 'input-oak-dark',
			src: '/pictures/combination/inputs/oak-dark.png',
		},
	],
	cabelArray: [
		{
			id: 'input-roke-white',
			src: '/pictures/combination/inputs/rope-white.png',
		},
		{
			id: 'input-roke-black',
			src: '/pictures/combination/inputs/rope-black.png',
		},
	],

	activeMaterial: 'input-oak-natural',
	activeCabel: 'input-roke-white',
}
export const ComplexSlice = createSlice({
	name: 'complex',
	initialState,
	reducers: {
		changeComplexActiveMaterial: (state, action: PayloadAction<string>) => {
			state.activeMaterial = action.payload
		},
		changeComplexActiveCabel: (state, action: PayloadAction<string>) => {
			state.activeCabel = action.payload
		},
	},
})

export const { changeComplexActiveMaterial, changeComplexActiveCabel } =
	ComplexSlice.actions

export default ComplexSlice.reducer
